QtcIndustries = {
    'feed': "http://www.starvingpoet.net/feeds/mmi.xml",
    'url': "http://www.starvingpoet.net/",
    'description': "MMI 7 day average",
    'name': "QTC Industries",
    'item_map': {
        'AlloyedTritaniumBar': 25595,
        'ArmorPlates': 25605,
        'BrokenDroneTransceiver': 25596,
        'BurnedLogicCircuit': 25600,
        'CharredMicroCircuit': 25599,
        'ConductivePolymer': 25604,
        'ContaminatedLorentzFluid': 25591,
        'ContaminatedNaniteCompound': 25590,
        'DamagedArtificialNeuralNetwork': 25597,
        'Datacore-AmarrianStarshipEngineering': 20421,
        'Datacore-CaldariStarshipEngineering': 25887,
        'Datacore-ElectromagneticPhysics': 20417,
        'Datacore-ElectronicEngineering': 20418,
        'Datacore-GallenteanStarshipEngineering': 20410, 
        'Datacore-GravitonPhysics': 20419,
        'Datacore-HighEnergyPhysics': 20411,
        'Datacore-HydromagneticPhysics': 20171,
        'Datacore-LaserPhysics': 20413,
        'Datacore-MechanicalEngineering': 20424, 
        'Datacore-MinmatarStarshipEngineering': 20172, 
        'Datacore-MolecularEngineering': 20415,
        'Datacore-NaniteEngineering': 20416,
        'Datacore-NuclearPhysics': 20423,
        'Datacore-PlasmaPhysics': 20412,
        'Datacore-QuantumPhysics': 20414,
        'Datacore-RocketScience': 20420,
        'DefectiveCurrentPump': 25592,
        'FriedInterfaceCircuit': 25601,
        'HeavyWater': 16272,
        'HeliumIsotopes': 16274,
        'HydrogenIsotopes': 17889,
        'HypersynapticFibers': 16682,
        'ImpetusConsole': 25621, 
        'Isogen': 37,
        'LiquidOzone': 16273,
        'MalfunctioningShieldEmitter': 25589,
        'Megacyte': 40,
        'MeltedCapacitorConsole': 25603,
        'Mexallon': 36,
        'Morphite': 11399,
        'Nanotransistors': 16681,
        'NitrogenIsotopes': 17888,
        'Nocxium': 38,
        'OxygenIsotopes': 17887,
        'Pyerite': 35,
        'ScorchedTelemetryProcessor': 25588,
        'Single-crystalSuperalloyI-beam': 25614,
        'SmashedTriggerUnit': 25593,
        'StrontiumClathrates': 16275,
        'TangledPowerConduit': 25594,
        'ThrusterConsole': 25602,
        'TriggerUnit': 25612,
        'TrippedPowerCircuit': 25598,
        'Tritanium': 34,
        'WardConsole': 25606,
        'Zydrine': 39,
    }
}

EveCentral = {
    'feed': "http://eve-central.com/home/marketstat_xml.html?regionlimit=%(region_id)s&typeid=%(item_id)s",
    'url': "http://www.eve-central.com/",
    'description': "Min/max sell/buy prices from %(region)s.",
    'name': "EVE Central: %(region)s",
    'regions': ({'name':'Domain',    'priority':151}, # Amarr: Amarr
                {'name':'The Forge', 'priority':154}, # Caldari: Jita
                {'name':'Heimatar',  'priority':152}, # Minmatar: Rens
                {'name':'Essence',   'priority':153}, # Gallente: Oursalert
                ),
    'categories': ('Charge','Drone','Commodity','Material','Implant','Ship'),
}