ore_map = {
    "A" : ("Veldspar", "Scordite",), 
    "B" : ("Veldspar", "Scordite", "Pyroxeres",), 
    "B1" : ("Veldspar", "Scordite", "Pyroxeres", "Kernite",), 
    "B2" : ("Veldspar", "Scordite", "Pyroxeres", "Kernite", "Jaspet",), 
    "B3" : ("Veldspar", "Scordite", "Pyroxeres", "Kernite", "Jaspet", "Hemorphite",), 
    "C" : ("Veldspar", "Scordite", "Plagioclase", "Pyroxeres",), 
    "C1" : ("Veldspar", "Scordite", "Plagioclase", "Pyroxeres", "Kernite",), 
    "C2" : ("Veldspar", "Scordite", "Plagioclase", "Pyroxeres", "Kernite", "Hedbergite",), 
    "D" : ("Veldspar", "Scordite", "Plagioclase",), 
    "D1" : ("Veldspar", "Scordite", "Plagioclase", "Omber",), 
    "D2" : ("Veldspar", "Scordite", "Plagioclase", "Omber", "Jaspet",), 
    "D3" : ("Veldspar", "Scordite", "Plagioclase", "Omber", "Jaspet", "Hemorphite",), 
    "E" : ("Veldspar", "Scordite", "Plagioclase", "Omber", "Kernite",), 
    "E1" : ("Veldspar", "Scordite", "Plagioclase", "Omber", "Kernite", "Hedbergite",), 
    "F" : ("Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber",), 
    "F1" : ("Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Spodumain",), 
    "F2" : ("Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Spodumain", "Gneiss",), 
    "F3" : ("Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Spodumain", "Gneiss", "Bistot",), 
    "F4" : ("Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Spodumain", "Gneiss", "Bistot", "Arkonor",), 
    "F5" : ("Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Spodumain", "Gneiss", "Bistot", "Arkonor", "Pyroxeres",), 
    "F6" : ("Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Spodumain", "Gneiss", "Bistot", "Arkonor", "Pyroxeres", "Mercoxit",), 
    "F7" : ("Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Spodumain", "Gneiss", "Bistot", "Arkonor", "Pyroxeres", "Mercoxit", "Plagioclase",), 
    "G" : ("Veldspar", "Scordite", "Plagioclase", "Omber", "Kernite",), 
    "G1" : ("Veldspar", "Scordite", "Plagioclase", "Omber", "Kernite", "Gneiss",), 
    "G2" : ("Veldspar", "Scordite", "Plagioclase", "Omber", "Kernite", "Gneiss", "Pyroxeres",), 
    "G3" : ("Veldspar", "Scordite", "Plagioclase", "Omber", "Kernite", "Gneiss", "Pyroxeres", "Spodumain",), 
    "G4" : ("Veldspar", "Scordite", "Plagioclase", "Omber", "Kernite", "Gneiss", "Pyroxeres", "Spodumain", "Bistot",), 
    "G5" : ("Veldspar", "Scordite", "Plagioclase", "Omber", "Kernite", "Gneiss", "Pyroxeres", "Spodumain", "Bistot", "Crokite",), 
    "G6" : ("Veldspar", "Scordite", "Plagioclase", "Omber", "Kernite", "Gneiss", "Pyroxeres", "Spodumain", "Bistot", "Crokite", "Mercoxit",), 
    "G7" : ("Veldspar", "Scordite", "Plagioclase", "Omber", "Kernite", "Gneiss", "Pyroxeres", "Spodumain", "Bistot", "Crokite", "Mercoxit", "Dark Ochre",), 
    "H" : ("Veldspar", "Scordite", "Pyroxeres", "Hemorphite", "Jaspet",), 
    "H1" : ("Veldspar", "Scordite", "Pyroxeres", "Hemorphite", "Jaspet", "Hedbergite",), 
    "H2" : ("Veldspar", "Scordite", "Pyroxeres", "Hemorphite", "Jaspet", "Hedbergite", "Dark Ochre",), 
    "H3" : ("Veldspar", "Scordite", "Pyroxeres", "Hemorphite", "Jaspet", "Hedbergite", "Dark Ochre", "Kernite",), 
    "H4" : ("Veldspar", "Scordite", "Pyroxeres", "Hemorphite", "Jaspet", "Hedbergite", "Dark Ochre", "Kernite", "Crokite",), 
    "H5" : ("Veldspar", "Scordite", "Pyroxeres", "Hemorphite", "Jaspet", "Hedbergite", "Dark Ochre", "Kernite", "Crokite", "Spodumain",), 
    "H6" : ("Veldspar", "Scordite", "Pyroxeres", "Hemorphite", "Jaspet", "Hedbergite", "Dark Ochre", "Kernite", "Crokite", "Spodumain", "Mercoxit",), 
    "H7" : ("Veldspar", "Scordite", "Pyroxeres", "Hemorphite", "Jaspet", "Hedbergite", "Dark Ochre", "Kernite", "Crokite", "Spodumain", "Mercoxit", "Bistot",), 
    "I" : ("Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber",), 
    "I1" : ("Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Jaspet",), 
    "I2" : ("Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Jaspet", "Spodumain",), 
    "I3" : ( "Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Jaspet", "Spodumain",),
    "I4" : ( "Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Jaspet", "Spodumain", "Gneiss", "Dark Ochre",),
    "I5" : ( "Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Jaspet", "Spodumain", "Gneiss", "Dark Ochre", "Arkonor",),
    "I6" : ( "Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Jaspet", "Spodumain", "Gneiss", "Dark Ochre", "Arkonor", "Mercoxit",),
    "I7" : ( "Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Jaspet", "Spodumain", "Gneiss", "Dark Ochre", "Arkonor", "Mercoxit", "Kernite",),
    "J" : ( "Veldspar", "Scordite", "Pyroxeres", "Plagioclase", "Jaspet",),
    "J1" : ( "Veldspar", "Scordite", "Pyroxeres", "Plagioclase", "Jaspet", "Dark Ochre",),
    "J2" : ( "Veldspar", "Scordite", "Pyroxeres", "Plagioclase", "Jaspet", "Dark Ochre", "Crokite",),
    "J3" : ( "Veldspar", "Scordite", "Pyroxeres", "Plagioclase", "Jaspet", "Dark Ochre", "Crokite", "Bistot",),
    "J4" : ( "Veldspar", "Scordite", "Pyroxeres", "Plagioclase", "Jaspet", "Dark Ochre", "Crokite", "Bistot", "Hemorphite",),
    "J5" : ( "Veldspar", "Scordite", "Pyroxeres", "Plagioclase", "Jaspet", "Dark Ochre", "Crokite", "Bistot", "Hemorphite", "Hedbergite",),
    "J6" : ( "Veldspar", "Scordite", "Pyroxeres", "Plagioclase", "Jaspet", "Dark Ochre", "Crokite", "Bistot", "Hemorphite", "Hedbergite", "Mercoxit",),
    "J7" : ( "Veldspar", "Scordite", "Pyroxeres", "Plagioclase", "Jaspet", "Dark Ochre", "Crokite", "Bistot", "Hemorphite", "Hedbergite", "Mercoxit", "Arkonor",),
    "K" : ( "Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber",),
    "K1" : ( "Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Dark Ochre",),
    "K2" : ( "Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Dark Ochre", "Spodumain",),
    "K3" : ( "Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Dark Ochre", "Spodumain", "Crokite",),
    "K4" : ( "Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Dark Ochre", "Spodumain", "Crokite", "Bistot",),
    "K5" : ( "Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Dark Ochre", "Spodumain", "Crokite", "Bistot", "Arkonor",),
    "K6" : ( "Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Dark Ochre", "Spodumain", "Crokite", "Bistot", "Arkonor", "Mercoxit",),
    "K7" : ( "Veldspar", "Scordite", "Hedbergite", "Hemorphite", "Omber", "Dark Ochre", "Spodumain", "Crokite", "Bistot", "Arkonor", "Mercoxit", "Gneiss"),
}
for key in ore_map:
    for v in ore_map[key]:
        print "%s = %s" % (key, v)  
 