USE eve;

RENAME TABLE
    agtagents TO ccp_agent,
    agtagenttypes TO ccp_agenttype,
    agtconfig TO ccp_agentconfig,
#             agtofferdetails TO ccp_agentoffer,
    agtResearchAgents to ccp_agentresearch,
    chrancestries TO ccp_characterancestry,
    chrattributes TO ccp_characterattribute,
    chrbloodlines TO ccp_characterbloodline,
    chrcareers TO ccp_charactercareer,
    chrcareerskills TO ccp_charactercareerskills,
    chrcareerspecialities TO ccp_charactercareerspeciality,
    chrcareerspecialityskills TO ccp_charactercareerspecialityskill,
    chrfactions TO ccp_faction,
    chrraces TO ccp_race,
    chrraceskills TO ccp_raceskill,
    chrschoolagents TO ccp_schoolagent,
    chrschools TO ccp_school,
    crpactivities TO ccp_corporationactivity,
    crpnpccorporationdivisions TO ccp_crpnpccorporationdivisions,
    crpnpccorporationresearchfields TO ccp_crpnpccorporationresearchfields,
    crpnpccorporations TO ccp_corporation,
    crpnpcdivisions TO ccp_corporationdivision,
#             crpnpccorporationtrades to ccp_corporationtrade,
#    dgmattributetypes TO ccp_attribute,
    dgmeffects TO ccp_effect,
    dgmtypeattributes TO ccp_typeattribute,
    dgmtypeeffects TO ccp_typeeffect,
    dgmattributecategories TO ccp_attributecatagory,
    evegraphics TO ccp_graphic,
    evenames TO ccp_name,
    eveunits TO ccp_unit,
    invblueprinttypes TO ccp_blueprintdetail,
    invcategories TO ccp_category,
    invcontrabandtypes TO ccp_contrabandtype,
    invcontroltowerresourcepurposes TO ccp_stationresourcepurpose,
    invcontroltowerresources TO ccp_stationresource,
    invflags TO ccp_flag,
    invgroups TO ccp_group,
    invmarketgroups TO ccp_marketgroup,
    invmetagroups TO ccp_inventorymetagroup,
    invmetatypes TO ccp_inventorymetatype,
    invtypereactions TO ccp_reaction,
    invtypes TO ccp_item,
    mapcelestialstatistics TO ccp_mapcelestialstatistics,
    mapconstellationjumps TO ccp_constellationjumps,
    mapconstellations TO ccp_constellation,
    mapdenormalize TO ccp_mapdenormalize,
    mapjumps TO ccp_jumps,
    maplandmarks TO ccp_landmarks,
    mapregionjumps TO ccp_regionjumps,
    mapregions TO ccp_region,
    mapsolarsystemjumps TO ccp_solarsystemjumps,
    mapsolarsystems TO ccp_solarsystem,
    mapuniverse TO ccp_mapuniverse,
    ramactivities TO ccp_ramactivity,
    ramassemblylines TO ccp_ramassemblyline,
#             ramassemblylinestationcostlogs TO ccp_ramassemblylinestationcostlog,
    ramassemblylinestations TO ccp_ramassemblylinestation,
    ramassemblylinetypedetailpercategory TO ccp_ramassemblylinetypedetailpercategory,
    ramassemblylinetypedetailpergroup TO ccp_ramassemblylinetypedetailpergroup,
    ramassemblylinetypes TO ccp_ramassemblylinetype,
#             ramcompletedstatuses TO ccp_ramcompletedstatus,
#             raminstallationtypedefaultcontents TO ccp_raminstallationtypedefaultcontent,
    staoperations TO ccp_stationoperation,
    staoperationservices TO ccp_stationoperationservice,
    staservices TO ccp_stationservice,
    stastations TO ccp_station,
    stastationtypes TO ccp_stationtype,
    typeActivityMaterials TO ccp_material,
    mapsecurityratings TO ccp_mapsecurityrating,
    crtcategories TO ccp_certificatecategory,
    crtcertificates TO ccp_certificate,
    crtclasses TO ccp_certificateclass,
    crtrelationships TO ccp_certificaterelation,

;